### ISSUE TITLE
 2.0.0-alpha-6 crashes

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/lwjgl3ify#121]
i get a crash with customnpcs
[crash-2024-02-15_08.03.42-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/14299023/crash-2024-02-15_08.03.42-client.txt)

and i remove custom npcs then i crash with smartmoving
[crash-2024-02-15_08.08.02-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/14299024/crash-2024-02-15_08.08.02-client.txt)

tested with java 21 and java 17

**Comment by eigenraven** [comment]
Should have already been fixed in latest alphas
