### ISSUE TITLE
2.0.0-alpha-8 multimc crash

### ISSUE THREAD

**Issue by smuurf-xyzz** [GTNewHorizons/lwjgl3ify#124]
I get weird crash when trynna launch game without any mods (and with mods same thing)
Logs: https://gist.github.com/smuurf-xyzz/2a9cbd07c584bfc9cd4025976a42220c
Java version: 17

**Comment by eigenraven** [comment]
There is pretty much no information in your log, please post the minecraft log (you can just copy from the console that should appear after the crash) instead of multimc's internal log

**Comment by smuurf-xyzz** [comment]
MC log: https://gist.github.com/smuurf-xyzz/e1c29aba7bf6640512ee4946a163e007
By the way with alpha-9 same crash

**Comment by eigenraven** [comment]
You need to use the java arguments from the `rfb` branch in multimc to use the alpha branch, not the current default README:
https://github.com/GTNewHorizons/lwjgl3ify/tree/rfb?tab=readme-ov-file#multimc-setup-gtnh-and-non-gtnh
