### ISSUE TITLE
ClassCircularityError on server in pack nightly 359

### ISSUE THREAD

**Issue by Caedis** [GTNewHorizons/lwjgl3ify#126]
Downgrading lwjgl3ify-2.0.0-alpha-8.jar to lwjgl3ify-1.5.16.jar (and changing the forgePatches jar back) fixed the issue

Crash log: https://mclo.gs/5qaInxu

Latest.log: https://mclo.gs/mp0mF4m

**Comment by msparkles** [comment]
Same issue here. Tried everything to fix it.

**Comment by eigenraven** [comment]
Should be fixed in alpha 9
