### ISSUE TITLE
lwjgl3ify breaks raw mouse input mod

### ISSUE THREAD

**Issue by Tree-er233** [GTNewHorizons/lwjgl3ify#129]
lwjgl3ify 2.0.0-alpha10 in GTNH 2.6.0 nightly 382, [rawinput 1.4.0](https://github.com/seanld03/RawInputMod-1.12.2-1.7.10/releases/tag/v1.4.0)

[fml-client-latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/14566502/fml-client-latest.log)

rawinput worked fine in GTNH 2.5.1 with lwjgl3ify 1.5.7, but no longer in GTNH 2.6.0.

**Comment by githubgarry73** [comment]
Can confirm, have the exact same problem now, worked perfect in 2.5.1

**Comment by eigenraven** [comment]
I've now added a raw mouse input toggle to the lwjgl3ify config, so the mod should no longer be needed.
