### ISSUE TITLE
Crash with arch linux

### ISSUE THREAD

**Issue by s0u7a** [GTNewHorizons/lwjgl3ify#134]
https://mclo.gs/iDYkFIC

mods:+unimixins-gtnhmixins-1.7.10-0.1.17+2.2.0.jar,gtnhlib-0.2.10.jar,hodgepodge-2.4.40.jar I followed the instructions here:https://github.com/ GTNewHorizons/lwjgl3ify?tab=readme-ov-file#server
Java:jre17-openjdk

**Comment by s0u7a** [comment]
I set unimixins to ALL, but now I get this error. https://mclo.gs/9AQZNWC

**Comment by eigenraven** [comment]
You have installed the forgePatches jar correctly, but are missing the main lwjgl3ify mod jar in `mods/`

**Comment by s0u7a** [comment]
I installed lwjgl3ify-2.0.2.jar in the mods directory but it still crashes

**Comment by s0u7a** [comment]
https://mclo.gs/0ooqQ3H

**Comment by eigenraven** [comment]
Now you're missing unimixins core again, did you install the base `mixin` module, or just the `gtnhmixin` extension? Because if you use the modular builds, you have to install the base too.

**Comment by s0u7a** [comment]
Is this it https://github.com/GTNewHorizons/GTNHMixins ?

**Comment by s0u7a** [comment]
fixed! Thank you so much!
