### ISSUE TITLE
Crash on startup (linux)

### ISSUE THREAD

**Issue by Rdf** [GTNewHorizons/lwjgl3ify#142]
At the end of last year, version of the game xxx (I don’t remember which) ran on java 17 without problems. Then I didn't run minecraft for a while and a couple of months ago I couldn't run version xxx. I haven't installed any new packages since then, so the problem is with one of the gentoo updates. Maybe from the log it will be possible to understand why the crash occurred?
[log.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/15213166/log.txt)

**Comment by eigenraven** [comment]
The log ends with "process exited with exit code 9" which is KILL, so your operating system is just killing MC. Most likely you just ran out of memory.

**Comment by Rdf** [comment]
I tried to set min/max 10240MB/20480MB. Did not help. lwjgl3ify has nothing to do with the sound system? I have a pure alsa without pulse/pipewire.

**Comment by eigenraven** [comment]
Can you check your system logs (`journalctl`, `dmesg`) after the game crashes to see if there's any information there?

**Comment by Rdf** [comment]
dmesg nothing was added after the crash. In the /var/log folder, the last modified file after the crash was 3 minutes ago (the moment the root session was opened to read the logs)

**Comment by Rdf** [comment]
Prism Launcher -> use OpenAL (system) -> all ok.
