### ISSUE TITLE
[2.1.2] Crash on startup with linux and prismlauncher

### ISSUE THREAD

**Issue by WolFWarr1oR** [GTNewHorizons/lwjgl3ify#172]
Logs: https://mclo.gs/rVrJCXp

Mods:
unimixins-all-1.7.10-0.1.17
gtnhlib-0.4.8
hodgepodge-2.5.50
lwjgl3ify-2.1.2
Thaumcraft-1.7.10-4.2.3.5

Tried with java-21 and java-17. Also tried to use different lwjgl3ify (2.0.9).
By the way, GTNH instance with java21 support didn't work for me too.

**Comment by eigenraven** [comment]
Something in your graphics drivers is preventing multithreaded opengl contexts, try disabling the fancy forge splash screen in `config/splash.properties`:
```
enabled=false
```

**Comment by WolFWarr1oR** [comment]
It started, there is sound, but no visible window. Is it a problem specifically on my side?

**Comment by eigenraven** [comment]
It seems like some sort of driver issue to me, can you check if vanilla minecraft 1.21 runs fine for you in prism?

**Comment by WolFWarr1oR** [comment]
Okay, it seems to be a problem with Wayland. Everything works on X11. Sorry for wasting your time.
