### ISSUE TITLE
[Crash] v1.1.31 crashes on startup with CoFHCore

### ISSUE THREAD

**Issue by 007killer2** [GTNewHorizons/lwjgl3ify#19]
Mods:

- CoFHCore 3.1.4-329
- GTNHMixins 2.1.13
- lwjgl3ify 1.1.31
- gtnhlib 0.0.12
- hodgepodge 2.0.36

Java:

- Oracle JDK 17.0.6
[log.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10795005/log.txt)

**Comment by eigenraven** [comment]
Fixed in 1.1.32
