### ISSUE TITLE
"Class bytes are null for org.spongepowered.asm.launch.MixinTweaker" Crash with only the needed mods installed.

### ISSUE THREAD

**Issue by PiBombbb** [GTNewHorizons/lwjgl3ify#191]
### Your GTNH Discord Username

PiBombbb#2012

### Mod Version

2.1.4

### Bug Report

https://mclo.gs/1GuawXP

### Java Version

GraalVM Early Access 24.0.0-ea.22 (Also tried with Adoptium Java 21.0.4.7, same crash)

### Operating System

Windows 10

### Keyboard Layout

English(UK)

### Mod List or GTNH Pack Version

![image](https://github.com/user-attachments/assets/a093f357-8838-43c0-97d2-4cb76a3e1b91)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by eigenraven** [comment]
You've installed the gtnhmixins unimixins module without the core module, either use the -all jar or install the main jar and the gtnhmixins jar like specified in the unimixins readme.
