### ISSUE TITLE
[Crash] Startup crash with lotr mod

### ISSUE THREAD

**Issue by mist475** [GTNewHorizons/lwjgl3ify#2]
[crashlog.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10500702/crashlog.txt)
Is this fixable on your end or would this require an lotr mod update?

Mods:
- GTNHMixins 2.1.11
- LOTR 36.15
- lwjgl3ify 1.1.7

Java version: Adoptium 19.0.2.7

**Comment by eigenraven** [comment]
One of the bugs early in the log should be fixed with 1.1.8, but LOTR needs to fix its final field reflection accesses like explained in <https://github.com/GTNewHorizons/lwjgl3ify/blob/master/README.MD#javabasejavalangreflect-classes-are-protected-from-reflective-access> to fix the crash.

**Comment by eigenraven** [comment]
Without a fix you can still use lwjgl3ify, but only up to java 11.
