### ISSUE TITLE
inputfix seems to be incompatible with lwjgl

### ISSUE THREAD

**Issue by mcmso** [GTNewHorizons/lwjgl3ify#20]
[crash-2023-02-22_18.34.22-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10803157/crash-2023-02-22_18.34.22-client.txt)
version:lwjgl3ify-1.1.32.jar
            InputFix-1.7.10-v5.jar
Please contact me if you need any additional information

**Comment by eigenraven** [comment]
What does inputfix fix exactly and is it still broken on lwjgl3ify without inputfix? Maybe I can integrate a fix directly into lwjgl3ify

**Comment by mcmso** [comment]
[inputfix](https://github.com/zlainsama/InputFix)
inputfix is a mod that allows Chinese players to input Chinese characters normally and allows us to input multi-byte Chinese characters

**Comment by HikerL** [comment]
> What does inputfix fix exactly and is it still broken on lwjgl3ify without inputfix? Maybe I can integrate a fix directly into lwjgl3ify

It helps Asian players from 1.6.x to 1.8.x to type Multi-Byte characters in game, for example, chinese and japanese.
This issues won't affect Latin alphabet users as ASCII is Single-Byte Character Set。

**Comment by HikerL** [comment]
Hope https://github.com/zlainsama/InputFix/commits?author=zlainsama can provide some support.

**Comment by HikerL** [comment]
Hope @zlainsama can provide some support in https://github.com/zlainsama/InputFix/issues/14 as the mod work perfectly since 2014

**Comment by eigenraven** [comment]
Do I understand correctly it adds a hotkey to show an input dialog for multibyte input?

**Comment by zlainsama** [comment]
So... just removing the exclusions would work? Could you include the patch?
I currently don't have a working 1.7.10 forge dev environment, could you point me to a guide?

**Comment by sousuke0422** [comment]
> So... just removing the exclusions would work? Could you include the patch? I currently don't have a working 1.7.10 forge dev environment, could you point me to a guide?

If you [add the repository](https://github.com/Roadhog360/Et-Futurum-Requiem/blob/dbaea20ce99cb16af19e98e15754500a2b251480/build.gradle#L9-L11) to build.gradle and [change the forge gradle version](https://github.com/Roadhog360/Et-Futurum-Requiem/blob/dbaea20ce99cb16af19e98e15754500a2b251480/build.gradle#L14), it should work. ~~It works fine if you don't modify forge. :)~~

[Or migrate to ExampleMod 1.7.10.](https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/docs/migration.md)

**Comment by eigenraven** [comment]
I made a pr: <https://github.com/zlainsama/InputFix/pull/15>

**Comment by zlainsama** [comment]
Merged, compiled, uploaded.

**Comment by RhythmNz** [comment]
still not work

**Comment by RhythmNz** [comment]
can't input chinese
