### ISSUE TITLE
Crash on startup with modpack

### ISSUE THREAD

**Issue by reuben-matus** [GTNewHorizons/lwjgl3ify#23]
Error on startup not sure if I was meant to unzip the zip when I placed it in the modpack folder but yeah here's the crash report if that helps:
https://paste.ee/p/8aE8k
(using hodge just makes different error)
https://paste.ee/p/k9UTP

**Comment by chochem** [comment]
you are using java 8

**Comment by reuben-matus** [comment]
Thanks, I just realised actually but pasting in the jvm arguments results in this error on java 19/17
![error jdk jvm 19](https://user-images.githubusercontent.com/126036543/221380110-2914077e-f5be-4d6d-9935-9aa2315692ee.png)
