### ISSUE TITLE
Java jvm arguments startup crash

### ISSUE THREAD

**Issue by reuben-matus** [GTNewHorizons/lwjgl3ify#24]
pasting in the jvm arguments results in this error on java 19/17
![error jdk jvm 19](https://user-images.githubusercontent.com/126036543/221380110-2914077e-f5be-4d6d-9935-9aa2315692ee.png)
Using no jvm arugments results in this error: (java 17 and 19)
https://paste.ee/p/IX5El

**Comment by reuben-matus** [comment]
Upon looking around I needed to update mmc-pack.json but this still results in this error:
https://paste.ee/p/6mHQZ

**Comment by eigenraven** [comment]
It seems you copied some sort of special non-breaking space/newline characters from the browser so java didn't split the arguments properly, try copying from a different browser or via another program such as notepad (copy in browser, paste in notepad, copy in notepad, paste in mmc)

**Comment by eigenraven** [comment]
oh, or alternatively put a space after every line, maybe java on windows doesn't split arguments with newlines from mmc

**Comment by reuben-matus** [comment]
Thanks this worked however even with these arugments working for some reason I still get this error:
https://paste.ee/p/ajIIs

**Comment by mitchej123** [comment]
Be sure to read the directions on installation here https://github.com/GTNewHorizons/lwjgl3ify -- multimc needs a small bit of effort to make it work

**Comment by reuben-matus** [comment]
Thanks yep I just needed to move the extracted patches folder to the modpack folder it all works fine now 🙏
Might as well ask here I guess but is there a way to make it work on the default minecraft launcher or only the 2 supported ones

**Comment by eigenraven** [comment]
Theoretically you can make it work on the vanilla launcher by adding some json metadata files like in multimc, but I haven't written them in the vanilla format
