### ISSUE TITLE
inputfix use in a java9+ environment will cause a crash

### ISSUE THREAD

**Issue by chixiguavv1** [GTNewHorizons/lwjgl3ify#25]
After beginning the single-player game, press ESC or wait for a while and it will crash.
![image](https://user-images.githubusercontent.com/115782245/221406933-777d260d-4216-436a-9c4e-d8cc0b2df72c.png)

**Comment by chixiguavv1** [comment]
without the mod ,I can't type Chinese in the game.
this is the crash report. 
[crash-2023-02-26_19.11.22-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10833546/crash-2023-02-26_19.11.22-client.txt)
[crash-2023-02-26_19.11.20-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10833547/crash-2023-02-26_19.11.20-client.txt)
[crash-2023-02-26_19.11.18-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10833548/crash-2023-02-26_19.11.18-client.txt)

**Comment by Glease** [comment]
Duplicate of #20. Update your inputfix.

**Comment by chixiguavv1** [comment]
I've upgraded but still nothing works, just not crashing anymore.
![image](https://user-images.githubusercontent.com/115782245/221409850-7739af6a-cb7c-4eec-b6b7-3eb1deed570d.png)

**Comment by chixiguavv1** [comment]
I still can't type any Chinese

**Comment by chixiguavv1** [comment]
In the latest 2.3.0.0-RC1 version, inputfix still has no effect.
