### ISSUE TITLE
Text input oddities on Linux

### ISSUE THREAD

**Issue by 40110** [GTNewHorizons/lwjgl3ify#28]
### Your Pack Version

2.3.0-RC1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Expected text input to behave normally.

Steps to reproduce:
- Run Arch Linux (haven't tested on other OSes)
- Set keyboard layout to DVORAK, example command for X: `setxkbmap -model abnt2 -layout br -variant dvorak` (for brazilian ABNT2 keyboard)
- Input text in-game: searching through NEI, writing in chat etc. (limiting max framerate makes effect more perceptible)

### The Reality

- Some characters are not input correctly, some are duplicated, others uppercased etc
- Whether on QWERTY or DVORAK, pressing CTRL seems to always input a comma character

### Your Proposal

Fix text input behavior to be the same as previous versions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
Related: <https://github.com/glfw/glfw/issues/1794>

**Comment by 40110** [comment]
Can confirm `XMODIFIERS="@im=null" prismlauncher` fixes the problem for me too

**Comment by Frefreak** [comment]
Setting `XMODIFIERS=@im=null` would totally disable input methods like fcitx though ([archlinux's wiki]).

[archlinux's wiki]: https://wiki.archlinux.org/title/Fcitx5

**Comment by eigenraven** [comment]
Can you try with lwjgl3ify 1.2.1 to see if the ime-disabling workaround is still needed? We rewrote the whole keyboard implementation to hopefully fix these bugs

**Comment by Frefreak** [comment]
The new version works like a charm (Tested both normal input and with input method on)
Thanks for all the hard works.
