### ISSUE TITLE
Crash with falsetweaks

### ISSUE THREAD

**Issue by unix-supremacist** [GTNewHorizons/lwjgl3ify#36]
lwjgl3ify version:1.1.37
falsepatternlib version: built from e239171 for java 19 fixes latest git as of making the issue
unimixins version: 0.1.5

[crash-2023-03-12_09.28.57-server.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10951266/crash-2023-03-12_09.28.57-server.txt)
[latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10951267/latest.log)

disabling everything in the falsetweaks config does not help with the crash

**Comment by chochem** [comment]
Lwjgl3ify currently depends on GTNHMixins

**Comment by eigenraven** [comment]
unimixins is fine, and we're moving to it this update anyway

**Comment by sousuke0422** [comment]
These corrections are needed. Someone needs to send a Pull Request.

https://github.com/sousuke0422/FalsePatternLib/commit/17954136388f65b2c035c9569ede09f0e7988f1b

**Comment by unix-supremacist** [comment]
> After adding compatibility with UniMixins, I was also able to run the falsepattern lib with the latest commit, and falsetweaks doesn't work for me either, **but my crash report is `completely different`:** https://pastebin.com/dKhCWZ0n
> 
> It says some kind of "LoadController", something about mixins and "ReEntrantTransformerError: Re-entrance error."

this is the error i got to, apparently something happened with my log uploads and i didnt notice because the crash report is empty and thats definitely the wrong log, i can try to get new logs some time later

**Comment by kotmatross28729** [comment]
> > After adding compatibility with UniMixins, I was also able to run the falsepattern lib with the latest commit, and falsetweaks doesn't work for me either, **but my crash report is `completely different`:** https://pastebin.com/dKhCWZ0n
> > It says some kind of "LoadController", something about mixins and "ReEntrantTransformerError: Re-entrance error."
> 
> this is the error i got to, apparently something happened with my log uploads and i didnt notice because the crash report is empty and thats definitely the wrong log, i can try to get new logs some time later

There seems to be no crash when using the latest versions of these mods ( lwjgl3ify 1.3.4, falsepattern lib 0.11.2 and falsetweaks 2.3.0)
I tested on java 20

**Comment by eigenraven** [comment]
Looks like it's been fixed upstream

**Comment by kotmatross28729** [comment]
I still think falsetweaks doesn't like lwjgl3ify , although it runs separately from everything, it causes a lot of problems on behalf of other mods.
list: https://pastebin.com/vxJtwZAg

This should probably be reported to falsetweaks itself, but maybe this is still a compatibility issue with lwjgl3ify
