### ISSUE TITLE
Crash with Chocopatcher asm

### ISSUE THREAD

**Issue by unix-supremacist** [GTNewHorizons/lwjgl3ify#37]
lwjgl3ify version:1.1.37

[crash-2023-03-12_09.40.39-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10951301/crash-2023-03-12_09.40.39-client.txt)
[latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/10951302/latest.log)

chickenchunks patcher has a very similar crash if anyone wants to take a look, but i'm not making a issue for it as i already made a pr replacing it in gtnh code chicken lib

**Comment by eigenraven** [comment]
Fixed in 2.0.0-alpha-7
