### ISSUE TITLE
Any plans for 1.12.2?

### ISSUE THREAD

**Issue by LasmGratel** [GTNewHorizons/lwjgl3ify#57]
Any plans for a patch on Minecraft 1.12.2? Both 1.12.2 and 1.7.10 are heavily-modded Minecraft versions, it would be a great help to run them on modern Java versions.

**Comment by eigenraven** [comment]
The CleanroomMC people have a somewhat working lwjgl3ify fork for 1.12.2 integrated into the cleanroom loader (backwards compatible forge update/replacement) - you can find more details there: <https://github.com/CleanroomMC/> but it's still work in progress as far as I know.
