### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by danbka33** [GTNewHorizons/lwjgl3ify#6]
Windows 11
Java 19.0.2
lwjgl3ify-1.1.13

The scroll in the waypoint list sometimes takes an inverse value (moves in the opposite direction from the scroll), the slider does not move smoothly.

https://youtu.be/EaXCDdrdQRs

**Comment by danbka33** [comment]
Maybe this is affected by full screen mode. I recorded the video in windowed mode, there was no inversion

**Comment by eigenraven** [comment]
Can you tell me what model of mouse you have? Just so I know what type of scrollwheel it would register as (discrete/smooth)

**Comment by danbka33** [comment]
A4Tech Bloody TL50 Terminator

**Comment by eigenraven** [comment]
Should be fixed in 1.1.14

**Comment by danbka33** [comment]
https://youtu.be/yGYUVG4I8OE
00:00-0:21 Just scroll down
00:22-00:33 Slowly scroll down
00:46-end Slowly scroll up

With a normal scroll, you can see that it jumps a little in the opposite direction. I don't use inversion.

**Comment by eigenraven** [comment]
The JM issue should be fixed by <https://github.com/GTNewHorizons/Hodgepodge/pull/169>
