### ISSUE TITLE
Crash with Botania

### ISSUE THREAD

**Issue by Radplay** [GTNewHorizons/lwjgl3ify#66]
Using lwjgl3ify 1.4.0 + Unimixins 0.1.9 alongside Botania 1.9.23-GTNH and Baubles 1.0.1.16 (also the GTNH fork) causes a crash. The game loads fine without lwjgl3ify.

Crash log: https://mclo.gs/bHzkpeA

Latest.log: https://mclo.gs/XYahKXt

**Comment by eigenraven** [comment]
For potion errors you also need to install Hodgepodge <https://github.com/GTNewHorizons/Hodgepodge/>, Botania is used in GTNH with lwjgl3ify and works fine.
