### ISSUE TITLE
Crash with inputfix

### ISSUE THREAD

**Issue by Seedking** [GTNewHorizons/lwjgl3ify#68]
[crash-2023-07-12_18.47.58-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/12027056/crash-2023-07-12_18.47.58-client.txt)
[latest.log](https://github.com/GTNewHorizons/lwjgl3ify/files/12027062/latest.log)

**Comment by SmileYik** [comment]
seems can direct input Chinese or other Asian Language without `inputfix` after use this project

**Comment by Seedking** [comment]
thank you very much  I will try deleting it next time

**Comment by eigenraven** [comment]
Inputfix shouldn't be needed anymore when lwjgl3ify is installed, lwjgl3ify can handle IME input like modern vanilla minecraft.
