### ISSUE TITLE
Issue when clicking on an item with the Ctrl key

### ISSUE THREAD

**Issue by danbka33** [GTNewHorizons/lwjgl3ify#7]
Windows 11
Java 19.0.2
lwjgl3ify-1.1.13

Java 8 (How should work): https://youtu.be/P8UTq_fKUgY
Java 19 (Issue): https://youtu.be/9Qzha9eRQHQ

**Comment by eigenraven** [comment]
InvTweaks was forcing a cursor movement, I turned it off in the inv tweaks pr
