### ISSUE TITLE
Where are we supposed to find the libraries the server needs?

### ISSUE THREAD

**Issue by Richard-Rogalski** [GTNewHorizons/lwjgl3ify#72]
Trying to install on a dedicated server, but I need the libraries. The README tells me to grab them from my 'client launcher'. In both Poly and Prism, after clicking the 'open libraries' button it opens and creates a folder but it's empty. There's an instance-agnostic libraries folder, in .local/share/PrismLauncher, but it doesn't contain anything related to lwjgl3. 

Is there an alternative way I can find the libraries I need? Where do these libraries come from, surely they're on my client instance *somewhere*. Or if there's a way to fetch them without a client, that'd work too :D

**Comment by Richard-Rogalski** [comment]
ok, looking around in the files in patches, I see URLs that I have to look through in a web browser to find the files I need bcz idk how to do it programatically. like I can `wget http://jenkins.usrv.eu:8081/nexus/content/groups/public/net/minecraft/launchwrapper/1.15/launchwrapper-1.15.jar`. Thiiiiiiis will take me a while

**Comment by Richard-Rogalski** [comment]
bah, well, I'm stuck at ` https://maven.minecraftforge.net/org/ow2/asm/asm/` as their webUI doesn't work and I can't correctly guess the filename. help would be appreciated :)

**Comment by eigenraven** [comment]
They're in the `libraries` folder where the launcher is installed, not the specific instance. You can also get them from the GTNH server archives, or the source for them in the DAXXL repo: https://github.com/GTNewHorizons/DreamAssemblerXXL/tree/master/server_assets/forge/libraries
