### ISSUE TITLE
if the window was not minimized at startup, then I can’t click Back to Game

### ISSUE THREAD

**Issue by kotmatross28729** [GTNewHorizons/lwjgl3ify#9]
Hello, I have a very strange problem with this mod.
If I start the game without minimizing the window, then when I try to enter the world, a menu will appear in which all the buttons work, except for back to game, if I minimize and expand the window back, then everything will be fine, and when creating the next worlds everything will be fine too.

https://user-images.githubusercontent.com/110309314/215848899-baf11910-b3cb-48be-b79c-16e7aeadc697.mp4

![2](https://user-images.githubusercontent.com/110309314/215848830-80adaae2-6d82-49d7-8c45-a588fc689430.png)
![1](https://user-images.githubusercontent.com/110309314/215848835-60960d06-b1c6-4c68-a814-84263f3a71ed.png)

windows 10
PrismLauncher Windows 6.1
lwjgl3ify 1.1.14 and GTNHMixins 2.1.11

**Comment by chochem** [comment]
It didnt minimize for me, but I also had it start like this (probably because I unfocussed) sometimes where I then couldn't click 'back to game' (or esc).

Just waiting a bit seems to work for some reason.

**Comment by eigenraven** [comment]
Ah the variable was set to false on startup and only updates when the OS notifies the window that it's state changes

**Comment by eigenraven** [comment]
Should be fixed in 1.1.15

**Comment by kotmatross28729** [comment]
Oh, thanks!
