### ISSUE TITLE
EnderIOAddons incompatibility (ItemStackHolder is null)

### ISSUE THREAD

**Issue by mts2200** [GTNewHorizons/lwjgl3ify#93]
The problem appears with the EnderIOAddons mod. When trying to register a recipe, all ItemStacks that must be retrieved with ObjectHolder = null. Without lwjgl3ify there is no such problem. Attached is the CrashReport and [link for problem code](https://github.com/HenryLoenwind/EnderIOAddons/blob/master/src/main/java/info/loenwind/enderioaddons/recipe/Recipes.java#L175-L176).
[crash-2023-11-22_18.18.17-client.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/13442219/crash-2023-11-22_18.18.17-client.txt)

**Comment by eigenraven** [comment]
Fixed in 2.0.0-alpha-6
